// <auto-generated />
using System;
using Lab2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab2.Migrations
{
    [DbContext(typeof(MoviesContext))]
    partial class MoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Lab2.Models.Movies.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Genre");

                    b.Property<string>("Name");

                    b.Property<string>("Poster");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Author = "Todd Phillips",
                            CreatedAt = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Crime , Drama , Thriller",
                            Name = "Joker",
                            Poster = "https://dz7u9q3vpd4eo.cloudfront.net/admin-uploads/posters/mxt_movies_poster/joker_dabf394a-d4f2-4b68-90e2-011ed6b54012_poster.png?d=270x360&q=20"
                        },
                        new
                        {
                            Id = -2,
                            Author = "David Leitch",
                            CreatedAt = new DateTime(2019, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Action , Adventure",
                            Name = "Fast & Furious Presents: Hobbs & Shaw",
                            Poster = "https://dz7u9q3vpd4eo.cloudfront.net/admin-uploads/posters/mxt_movies_poster/fast-furious-presents-hobbs-shaw_14d1ab4f-c90c-46d1-9e04-f7d69f285ebd_poster.png?d=270x360&q=20"
                        },
                        new
                        {
                            Id = -3,
                            Author = "Jon Favreau",
                            CreatedAt = new DateTime(2019, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Adventure , Animation , Drama , Family , Musical",
                            Name = "The Lion King",
                            Poster = "https://dz7u9q3vpd4eo.cloudfront.net/admin-uploads/posters/mxt_movies_poster/the-lion-king_3904aadc-3a07-4836-892f-763b2dfdeea3_poster.png?d=270x360&q=20"
                        },
                        new
                        {
                            Id = -4,
                            Author = "Joachim Rønning",
                            CreatedAt = new DateTime(2019, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Adventure , Family , Fantasy",
                            Name = "Maleficent: Mistress of Evil",
                            Poster = "https://dz7u9q3vpd4eo.cloudfront.net/admin-uploads/posters/mxt_movies_poster/maleficent-mistress-of-evil_c8507e61-a6b3-404d-b8c5-df6f74bc62be_poster.png?d=270x360&q=20"
                        },
                        new
                        {
                            Id = -5,
                            Author = "Tobey Maguire",
                            CreatedAt = new DateTime(2002, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Superhero, Drama, Sci-FI",
                            Name = "Spider-man",
                            Poster = "http://www.gstatic.com/tv/thumb/v22vodart/29821/p29821_v_v8_ae.jpg"
                        },
                        new
                        {
                            Id = -6,
                            Author = "Rober Dawney Jr",
                            CreatedAt = new DateTime(2008, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Superhero,Drama,Sci-FI, Fantasy, Action",
                            Name = "Iron man",
                            Poster = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4mi0mHK2Yz9yXZ4poPAc0mRmVe8KtPfrhjXPOQL1dEw6C4qIZaA&s"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
